name: build-test

on: [pull_request]

jobs:
  build: 
    runs-on: unbuntu-latest
    strategy: 
      matrix: 
        node: ['16']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 16
        uses: actions/setuo-node@v2
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run lint